language: python

services:
  - docker

python:
  - "2.7"

install:
  - make deps

script:
  - make test_xunit
  - make lint
  		

after_success:
  - make docker_build
  - make docker_push

deploy:
  provider: heroku
  app: arcane-ocean-59910
  api_key: ${HEROKU_API_KEY}
